version: '3.3'

services:
  db:
    image: postgres:15.1
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgres/data/
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: danis
      POSTGRES_PASSWORD: danis
      POSTGRES_DB: danis
    healthcheck:
      test: pg_isready -U danis -d danis
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
